# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Observation.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5.QtWidgets import QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
import yaml

class Ui_ObservationUI(object):

    # def __init__(self, parent=None):
    #     super(Ui_ObservationUI, self).__init__(parent)
    #     self.setupUi(self)

    def setupUi(self, ObservationUI):
        ObservationUI.setObjectName("ObservationUI")
        ObservationUI.resize(640, 480)
        ObservationUI.setMinimumSize(QtCore.QSize(640, 480))
        ObservationUI.setMaximumSize(QtCore.QSize(640, 480))
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(ObservationUI)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 440, 621, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_2.addWidget(self.startButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.line = QtWidgets.QFrame(ObservationUI)
        self.line.setGeometry(QtCore.QRect(0, 110, 621, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayoutWidget = QtWidgets.QWidget(ObservationUI)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.modeLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.modeLayout.setContentsMargins(0, 0, 0, 0)
        self.modeLayout.setObjectName("modeLayout")
        self.modeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modeLabel.setFont(font)
        self.modeLabel.setObjectName("modeLabel")
        self.modeLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.modeLabel)
        self.gameModeBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.gameModeBox.setObjectName("gameModeBox")
        self.gameModeBox.addItem("")
        self.gameModeBox.addItem("")
        self.modeLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gameModeBox)
        self.levelLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.levelLabel.setFont(font)
        self.levelLabel.setObjectName("levelLabel")
        self.modeLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.levelLabel)
        self.levelBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.levelBox.setObjectName("levelBox")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.modeLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.levelBox)
        self.levelDescLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.levelDescLabel.setText("")
        self.levelDescLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.levelDescLabel.setObjectName("levelDescLabel")
        self.modeLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.levelDescLabel)
        self.formLayoutWidget_3 = QtWidgets.QWidget(ObservationUI)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(370, 130, 261, 201))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.subjectLayout1_2 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.subjectLayout1_2.setContentsMargins(0, 0, 0, 0)
        self.subjectLayout1_2.setVerticalSpacing(20)
        self.subjectLayout1_2.setObjectName("subjectLayout1_2")
        self.kanaLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kanaLabel.setFont(font)
        self.kanaLabel.setObjectName("kanaLabel")
        self.subjectLayout1_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kanaLabel)
        self.kanaBox = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.kanaBox.setObjectName("kanaBox")
        self.subjectLayout1_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kanaBox)
        self.sleepLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sleepLabel.setFont(font)
        self.sleepLabel.setObjectName("sleepLabel")
        self.subjectLayout1_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sleepLabel)
        self.sleepBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.sleepBox.setObjectName("sleepBox")
        self.subjectLayout1_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sleepBox)
        self.sexLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sexLabel.setFont(font)
        self.sexLabel.setObjectName("sexLabel")
        self.subjectLayout1_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sexLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 150, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sexBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.sexBox.setObjectName("sexBox")
        self.sexBox.addItem("")
        self.sexBox.addItem("")
        self.horizontalLayout_3.addWidget(self.sexBox)
        self.subjectLayout1_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.handFootLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.handFootLabel.setFont(font)
        self.handFootLabel.setObjectName("handFootLabel")
        self.subjectLayout1_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.handFootLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.handFootBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.handFootBox.setObjectName("handFootBox")
        self.handFootBox.addItem("")
        self.handFootBox.addItem("")
        self.horizontalLayout_5.addWidget(self.handFootBox)
        self.subjectLayout1_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.subjectLayout1_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.dominantHandBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.dominantHandBox.setObjectName("dominantHandBox")
        self.dominantHandBox.addItem("")
        self.dominantHandBox.addItem("")
        self.horizontalLayout_6.addWidget(self.dominantHandBox)
        self.subjectLayout1_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(ObservationUI)
        self.line_2.setGeometry(QtCore.QRect(10, 340, 621, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(ObservationUI)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 130, 330, 201))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.subjectLayout1 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.subjectLayout1.setContentsMargins(0, 0, 0, 0)
        self.subjectLayout1.setHorizontalSpacing(6)
        self.subjectLayout1.setVerticalSpacing(20)
        self.subjectLayout1.setObjectName("subjectLayout1")
        self.idLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        self.subjectLayout1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.idLabel)
        self.idBox = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.idBox.setObjectName("idBox")
        self.subjectLayout1.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idBox)
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.subjectLayout1.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameBox = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nameBox.setObjectName("nameBox")
        self.subjectLayout1.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameBox)
        self.bdLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bdLabel.setFont(font)
        self.bdLabel.setObjectName("bdLabel")
        self.subjectLayout1.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bdLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bdYearBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.bdYearBox.setObjectName("bdYearBox")
        self.horizontalLayout.addWidget(self.bdYearBox)
        self.bdMonthBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.bdMonthBox.setObjectName("bdMonthBox")
        self.horizontalLayout.addWidget(self.bdMonthBox)
        self.bdDayBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.bdDayBox.setObjectName("bdDayBox")
        self.horizontalLayout.addWidget(self.bdDayBox)
        self.subjectLayout1.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.heightLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.heightLabel.setFont(font)
        self.heightLabel.setObjectName("heightLabel")
        self.subjectLayout1.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.heightLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 150, -1)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.heightBox = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.heightBox.setObjectName("heightBox")
        self.horizontalLayout_4.addWidget(self.heightBox)
        self.cmLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.cmLabel.setObjectName("cmLabel")
        self.horizontalLayout_4.addWidget(self.cmLabel)
        self.subjectLayout1.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.weightLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weightLabel.setFont(font)
        self.weightLabel.setObjectName("weightLabel")
        self.subjectLayout1.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.weightLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 150, -1)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.weightBox = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.weightBox.setObjectName("weightBox")
        self.horizontalLayout_7.addWidget(self.weightBox)
        self.kgLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.kgLabel.setObjectName("kgLabel")
        self.horizontalLayout_7.addWidget(self.kgLabel)
        self.subjectLayout1.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.formLayoutWidget_4 = QtWidgets.QWidget(ObservationUI)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 360, 621, 73))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.commentBox = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.commentBox.setObjectName("commentBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.commentBox)
        self.commentField = QtWidgets.QPlainTextEdit(self.formLayoutWidget_4)
        self.commentField.setObjectName("commentField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.commentField)
        self.formLayoutWidget_5 = QtWidgets.QWidget(ObservationUI)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 90, 181, 21))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(25)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.feedBackBox = QtWidgets.QCheckBox(self.formLayoutWidget_5)
        self.feedBackBox.setText("")
        self.feedBackBox.setObjectName("feedBackBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.feedBackBox)
        self.formLayoutWidget_6 = QtWidgets.QWidget(ObservationUI)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(370, 90, 181, 21))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(15)
        self.formLayout_3.setObjectName("formLayout_3")
        self.distractionLabel = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.distractionLabel.setFont(font)
        self.distractionLabel.setObjectName("distractionLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.distractionLabel)
        self.distractionBox = QtWidgets.QCheckBox(self.formLayoutWidget_6)
        self.distractionBox.setText("")
        self.distractionBox.setObjectName("distractionBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.distractionBox)

        self.retranslateUi(ObservationUI)
        QtCore.QMetaObject.connectSlotsByName(ObservationUI)

    def retranslateUi(self, ObservationUI):
        _translate = QtCore.QCoreApplication.translate
        ObservationUI.setWindowTitle(_translate("ObservationUI", "Form"))
        self.startButton.setText(_translate("ObservationUI", "始める"))
        self.cancelButton.setText(_translate("ObservationUI", "キャンセル"))
        self.modeLabel.setText(_translate("ObservationUI", "モード"))
        self.gameModeBox.setItemText(0, _translate("ObservationUI", "Mogura"))
        self.gameModeBox.setItemText(1, _translate("ObservationUI", "Gaze"))
        self.levelLabel.setText(_translate("ObservationUI", "レベル"))
        self.levelBox.setItemText(0, _translate("ObservationUI", "Default"))
        self.levelBox.setItemText(1, _translate("ObservationUI", "Easy"))
        self.levelBox.setItemText(2, _translate("ObservationUI", "Medium"))
        self.levelBox.setItemText(3, _translate("ObservationUI", "Hard"))
        self.levelBox.setItemText(4, _translate("ObservationUI", "Unbalance cat"))
        self.levelBox.setItemText(5, _translate("ObservationUI", "Unbalance chicken"))
        self.levelBox.setItemText(6, _translate("ObservationUI", "Children"))
        self.levelBox.setItemText(7, _translate("ObservationUI", "Children-Sym-Asym"))
        self.kanaLabel.setText(_translate("ObservationUI", "カナ"))
        self.kanaBox.setText(_translate("ObservationUI", "かな"))
        self.sleepLabel.setText(_translate("ObservationUI", "睡眠時間"))
        self.sexLabel.setText(_translate("ObservationUI", "性別"))
        self.sexBox.setItemText(0, _translate("ObservationUI", "M"))
        self.sexBox.setItemText(1, _translate("ObservationUI", "F"))
        self.handFootLabel.setText(_translate("ObservationUI", "手か足"))
        self.handFootBox.setItemText(0, _translate("ObservationUI", "手"))
        self.handFootBox.setItemText(1, _translate("ObservationUI", "足"))
        self.label_3.setText(_translate("ObservationUI", "利き手"))
        self.dominantHandBox.setItemText(0, _translate("ObservationUI", "右手"))
        self.dominantHandBox.setItemText(1, _translate("ObservationUI", "左手"))
        self.idLabel.setText(_translate("ObservationUI", "ID"))
        self.nameLabel.setText(_translate("ObservationUI", "名前"))
        self.nameBox.setText(_translate("ObservationUI", "名前"))
        self.bdLabel.setText(_translate("ObservationUI", "生年月日"))
        self.heightLabel.setText(_translate("ObservationUI", "身長"))
        self.heightBox.setText(_translate("ObservationUI", "0.0"))
        self.cmLabel.setText(_translate("ObservationUI", "Cm"))
        self.weightLabel.setText(_translate("ObservationUI", "体重"))
        self.weightBox.setText(_translate("ObservationUI", "0.0"))
        self.kgLabel.setText(_translate("ObservationUI", "Kg"))
        self.commentBox.setText(_translate("ObservationUI", "コメント"))
        self.label.setText(_translate("ObservationUI", "手応え"))
        self.distractionLabel.setText(_translate("ObservationUI", "気晴らし"))


        #setting the values
        self.setBDBoxes(_translate)
        self.setSleepingTime(_translate)
        self.setId()
        self.defaultLevelDesc()


    def defaultLevelDesc(self):
        self.levelDescLabel.setText("10分\t\t\t最大待ち時間=1.0s\t\t\t最小待ち時間=0.7s\t\t\t提示時間=0.7s\t\t\t鳥の割合=50")
    def setBDBoxes(self, _translate):
        minYear = 1950

        #set year values
        self.bdYearBox.addItem("")
        self.bdYearBox.setItemText(0, _translate("ObservationUI", "Year"))
        j = 1
        for i in range(minYear, datetime.today().year):
            self.bdYearBox.addItem("")
            self.bdYearBox.setItemText(j, _translate("ObservationUI", str(i)))
            j+=1

        # set month values
        self.bdMonthBox.addItem("")
        self.bdMonthBox.setItemText(0, _translate("ObservationUI", "Month"))
        for i in range(1, 13):
            self.bdMonthBox.addItem("")
            self.bdMonthBox.setItemText(i, _translate("ObservationUI", str(i)))

        # set day values
        self.bdDayBox.addItem("")
        self.bdDayBox.setItemText(0, _translate("ObservationUI", "Day"))
        for i in range(1, 32):
            self.bdDayBox.addItem("")
            self.bdDayBox.setItemText(i, _translate("ObservationUI", str(i)))


    def setSleepingTime(self, _translate):
        minSleep = 0.5
        j=0
        while (minSleep <= 15):
            self.sleepBox.addItem("")
            self.sleepBox.setItemText(j, _translate("ObservationUI", str(minSleep) + " 時間"))
            minSleep += 0.5
            j+=1


    def setId(self):
        f = open("conf/IdCounter.txt", "r+")
        lastID = f.readlines()[-1]
        id = lastID.split("_")[0]
        num = int(lastID.split("_")[-1])
        currentId = id + "_" + str(num+1).rjust(6, "0")

        self.idBox.setText(currentId)

        self.idBox.setEnabled(False)



