# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class Ui_MainWindow(QMainWindow):

    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.setupUi(self)
        self.setUpGraph()



    def setUpGraph(self):
        # setup response graph
        self.figureResponse = Figure(figsize=(5, 4), dpi=100)

        self.canvasResponse = FigureCanvas(self.figureResponse)
        self.canvasResponse.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.responseGraphLayout.addWidget(self.canvasResponse)

        # setup times graph
        self.figureTime = Figure(figsize=(5, 4), dpi=100)

        self.canvasTime = FigureCanvas(self.figureTime)
        self.canvasTime.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.timeGraphLayout.addWidget(self.canvasTime)

        # setup gaze graph
        self.figureGaze = Figure(figsize=(5, 4), dpi=100)

        self.canvasGaze = FigureCanvas(self.figureGaze)
        self.canvasGaze.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.gazeDistributionLayout.addWidget(self.canvasGaze)

        # setup head graph
        self.figureHead = Figure(figsize=(5, 4), dpi=100)

        self.canvasHead = FigureCanvas(self.figureHead)
        self.canvasHead.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.headMovementsLayout.addWidget(self.canvasHead)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1046, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1046, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1046, 768))
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1031, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.correctGroup = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.correctGroup.setFont(font)
        self.correctGroup.setObjectName("correctGroup")
        self.gridLayoutWidget = QtWidgets.QWidget(self.correctGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 491, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(11)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.corAvgField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.corAvgField.setEnabled(False)
        self.corAvgField.setAutoFillBackground(False)
        self.corAvgField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.corAvgField.setObjectName("corAvgField")
        self.gridLayout.addWidget(self.corAvgField, 0, 1, 1, 1)
        self.corAvgTimeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.corAvgTimeLabel.setObjectName("corAvgTimeLabel")
        self.gridLayout.addWidget(self.corAvgTimeLabel, 0, 2, 1, 1)
        self.corVarLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.corVarLabel.setObjectName("corVarLabel")
        self.gridLayout.addWidget(self.corVarLabel, 1, 0, 1, 1)
        self.corStdTimeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.corStdTimeLabel.setObjectName("corStdTimeLabel")
        self.gridLayout.addWidget(self.corStdTimeLabel, 1, 2, 1, 1)
        self.corAvgLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.corAvgLabel.setObjectName("corAvgLabel")
        self.gridLayout.addWidget(self.corAvgLabel, 0, 0, 1, 1)
        self.corStdField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.corStdField.setEnabled(False)
        self.corStdField.setAutoFillBackground(False)
        self.corStdField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.corStdField.setObjectName("corStdField")
        self.gridLayout.addWidget(self.corStdField, 1, 1, 1, 1)
        self.corAvgTimeField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.corAvgTimeField.setEnabled(False)
        self.corAvgTimeField.setAutoFillBackground(False)
        self.corAvgTimeField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.corAvgTimeField.setObjectName("corAvgTimeField")
        self.gridLayout.addWidget(self.corAvgTimeField, 0, 3, 1, 1)
        self.corStdTimeField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.corStdTimeField.setEnabled(False)
        self.corStdTimeField.setAutoFillBackground(False)
        self.corStdTimeField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.corStdTimeField.setObjectName("corStdTimeField")
        self.gridLayout.addWidget(self.corStdTimeField, 1, 3, 1, 1)
        self.horizontalLayout.addWidget(self.correctGroup)
        self.wrongGroup = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wrongGroup.setFont(font)
        self.wrongGroup.setObjectName("wrongGroup")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.wrongGroup)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 491, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(11)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wroAvgField = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.wroAvgField.setEnabled(False)
        self.wroAvgField.setAutoFillBackground(False)
        self.wroAvgField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.wroAvgField.setObjectName("wroAvgField")
        self.gridLayout_2.addWidget(self.wroAvgField, 0, 1, 1, 1)
        self.wroAvgTimeLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.wroAvgTimeLabel.setObjectName("wroAvgTimeLabel")
        self.gridLayout_2.addWidget(self.wroAvgTimeLabel, 0, 2, 1, 1)
        self.wroVarLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.wroVarLabel.setObjectName("wroVarLabel")
        self.gridLayout_2.addWidget(self.wroVarLabel, 1, 0, 1, 1)
        self.wroStdTimeLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.wroStdTimeLabel.setObjectName("wroStdTimeLabel")
        self.gridLayout_2.addWidget(self.wroStdTimeLabel, 1, 2, 1, 1)
        self.wroAvgLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.wroAvgLabel.setObjectName("wroAvgLabel")
        self.gridLayout_2.addWidget(self.wroAvgLabel, 0, 0, 1, 1)
        self.wroStdField = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.wroStdField.setEnabled(False)
        self.wroStdField.setAutoFillBackground(False)
        self.wroStdField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.wroStdField.setObjectName("wroStdField")
        self.gridLayout_2.addWidget(self.wroStdField, 1, 1, 1, 1)
        self.wroAvgTimeField = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.wroAvgTimeField.setEnabled(False)
        self.wroAvgTimeField.setAutoFillBackground(False)
        self.wroAvgTimeField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.wroAvgTimeField.setObjectName("wroAvgTimeField")
        self.gridLayout_2.addWidget(self.wroAvgTimeField, 0, 3, 1, 1)
        self.wroStdTimeField = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.wroStdTimeField.setEnabled(False)
        self.wroStdTimeField.setAutoFillBackground(False)
        self.wroStdTimeField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.wroStdTimeField.setObjectName("wroStdTimeField")
        self.gridLayout_2.addWidget(self.wroStdTimeField, 1, 3, 1, 1)
        self.horizontalLayout.addWidget(self.wrongGroup)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 110, 531, 109))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 491, 81))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(11)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.missLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.missLabel.setObjectName("missLabel")
        self.gridLayout_3.addWidget(self.missLabel, 0, 0, 1, 1)
        self.missField = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.missField.setEnabled(False)
        self.missField.setAutoFillBackground(False)
        self.missField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.missField.setObjectName("missField")
        self.gridLayout_3.addWidget(self.missField, 0, 1, 1, 1)
        self.avgTimeLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.avgTimeLabel.setObjectName("avgTimeLabel")
        self.gridLayout_3.addWidget(self.avgTimeLabel, 0, 2, 1, 1)
        self.stdTimeLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.stdTimeLabel.setObjectName("stdTimeLabel")
        self.gridLayout_3.addWidget(self.stdTimeLabel, 1, 2, 1, 1)
        self.avgTimeField = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.avgTimeField.setEnabled(False)
        self.avgTimeField.setAutoFillBackground(False)
        self.avgTimeField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.avgTimeField.setObjectName("avgTimeField")
        self.gridLayout_3.addWidget(self.avgTimeField, 0, 3, 1, 1)
        self.stdTimeField = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.stdTimeField.setEnabled(False)
        self.stdTimeField.setAutoFillBackground(False)
        self.stdTimeField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.stdTimeField.setObjectName("stdTimeField")
        self.gridLayout_3.addWidget(self.stdTimeField, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.trajectoryAreaField = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.trajectoryAreaField.setEnabled(False)
        self.trajectoryAreaField.setAutoFillBackground(False)
        self.trajectoryAreaField.setStyleSheet("background-color: rgb(255, 247, 188);")
        self.trajectoryAreaField.setObjectName("trajectoryAreaField")
        self.gridLayout_3.addWidget(self.trajectoryAreaField, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 220, 1031, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 690, 1021, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.trainingButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trainingButton.setFont(font)
        self.trainingButton.setObjectName("trainingButton")
        self.horizontalLayout_2.addWidget(self.trainingButton)
        self.observationButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.observationButton.setFont(font)
        self.observationButton.setObjectName("observationButton")
        self.horizontalLayout_2.addWidget(self.observationButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(530, 250, 501, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.timeGraphLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.timeGraphLayout.setContentsMargins(0, 0, 0, 0)
        self.timeGraphLayout.setObjectName("timeGraphLayout")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 501, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.responseGraphLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.responseGraphLayout.setContentsMargins(0, 0, 0, 0)
        self.responseGraphLayout.setObjectName("responseGraphLayout")
        self.responseGraphLabel = QtWidgets.QLabel(self.centralwidget)
        self.responseGraphLabel.setGeometry(QtCore.QRect(10, 230, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.responseGraphLabel.setFont(font)
        self.responseGraphLabel.setObjectName("responseGraphLabel")
        self.timeGraphLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeGraphLabel.setGeometry(QtCore.QRect(530, 230, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeGraphLabel.setFont(font)
        self.timeGraphLabel.setObjectName("timeGraphLabel")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 480, 501, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.headMovementsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.headMovementsLayout.setContentsMargins(0, 0, 0, 0)
        self.headMovementsLayout.setObjectName("headMovementsLayout")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(530, 480, 501, 201))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.gazeDistributionLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.gazeDistributionLayout.setContentsMargins(0, 0, 0, 0)
        self.gazeDistributionLayout.setObjectName("gazeDistributionLayout")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 450, 1031, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gazeDistributionLabel = QtWidgets.QLabel(self.centralwidget)
        self.gazeDistributionLabel.setGeometry(QtCore.QRect(530, 460, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gazeDistributionLabel.setFont(font)
        self.gazeDistributionLabel.setObjectName("gazeDistributionLabel")
        self.headMovementsLabel = QtWidgets.QLabel(self.centralwidget)
        self.headMovementsLabel.setGeometry(QtCore.QRect(10, 460, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.headMovementsLabel.setFont(font)
        self.headMovementsLabel.setObjectName("headMovementsLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1046, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuResults = QtWidgets.QMenu(self.menubar)
        self.menuResults.setObjectName("menuResults")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuResults.addAction(self.actionPrint)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuResults.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainUI"))
        self.correctGroup.setTitle(_translate("MainWindow", "正答"))
        self.corAvgTimeLabel.setText(_translate("MainWindow", "平均反応時間"))
        self.corVarLabel.setText(_translate("MainWindow", "ばらつき"))
        self.corStdTimeLabel.setText(_translate("MainWindow", "ばらつき反応時間"))
        self.corAvgLabel.setText(_translate("MainWindow", "平均（％）"))
        self.wrongGroup.setTitle(_translate("MainWindow", "総合エラー"))
        self.wroAvgTimeLabel.setText(_translate("MainWindow", "平均反応時間"))
        self.wroVarLabel.setText(_translate("MainWindow", "ばらつき"))
        self.wroStdTimeLabel.setText(_translate("MainWindow", "ばらつき反応時間"))
        self.wroAvgLabel.setText(_translate("MainWindow", "平均(%)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "全体"))
        self.missLabel.setText(_translate("MainWindow", "見逃し"))
        self.avgTimeLabel.setText(_translate("MainWindow", "平均反応時間"))
        self.stdTimeLabel.setText(_translate("MainWindow", "ばらつき反応時間"))
        self.label.setText(_translate("MainWindow", "視線のエリア"))
        self.trainingButton.setText(_translate("MainWindow", "練習"))
        self.observationButton.setText(_translate("MainWindow", "評価"))
        self.responseGraphLabel.setText(_translate("MainWindow", "正答率"))
        self.timeGraphLabel.setText(_translate("MainWindow", "反応時間"))
        self.gazeDistributionLabel.setText(_translate("MainWindow", "全ての視線の軌跡"))
        self.headMovementsLabel.setText(_translate("MainWindow", "視線の軌跡"))
        self.menuFile.setTitle(_translate("MainWindow", "ファイル"))
        self.menuResults.setTitle(_translate("MainWindow", "結果"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
