GAME_DIR: "Games\\AttentionTest_Mogura\\"
GAME_DIR_GAZE: "Games\\AttentionTest_Mogura_Gaze\\"
GAME_FILE: "MoleAttention.exe"
GAME_RESULT_DIR: "MoleAttention_Data\\result\\"
GAME_RESULTS_FILE: "gameResults.csv"
GAZE_HEAD_FILE: "gazeHeadPose.csv"
TRAINING_RESULT: "Results\\TrainingResults\\"
TRAINING_VIDEO_RESULTS:  "Results\\TrainingResults\\Videos"
EVALUATION_RESULTS:  "Results\\EvaluationResults\\"
EVALUATION_VIDEO_RESULTS:  "Results\\EvaluationResults\\Videos"
DB_PATH: "DB\\AttentionTestDB"
TURNF_FILES: "TurnsFiles"
